# Generated by Django 5.0.1 on 2024-01-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
