# Generated by Django 5.0.1 on 2024-01-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_portafolio', '0003_post_created_date_post_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=13)),
                ('age', models.IntegerField()),
                ('content', models.TextField()),
                ('skills', models.TextField()),
            ],
        ),
    ]
